### ISSUE TITLE
Assign default CSS to components

### ISSUE THREAD

**Issue by waldemarennsaed** [softwarecrafts/tailwind-component-classes#15]
I am wondering if it's possible to assign default CSS to the `components`, e.g.:

```javascript
// components
  components: {
    default: {
      backgroundColor: '#fff'
    },
    interaction: 'bg-white'
  }
```

In my case, I am using your amazing plugin for whitelabeling purposes, where themes can be exchanged by using a `.env` variable `THEME` -  and depending on that `THEME` variable, I sometimes need to just pass tw-classes like `bg-white` to my custom components and sometimes I need to directly assign a CSS value like `background-color`, since my base tw config doesn't include the whitelabel colors as such for colors - so I technically can't just use `bg-whitelabel-color-x`.

**Comment by nanorepublica** [comment]
Would it be possible to create a play.tailwindcss.com example of what you would like to see? Even if it's broken, I am struggling to see what you want to achieve.

**Comment by waldemarennsaed** [comment]
Not sure if this is sufficient (not sure if I can install your plugin on play.tailwindcss.com?):
https://play.tailwindcss.com/ZO0GIZq5bd?file=config

Basically talking about this specific case:
```
components: {
    'btn-white': {
      backgroundColor: '#fff'
    },
    'btn-black': 'bg-black' 
  },
```

**Comment by nanorepublica** [comment]
Would this work? Using the tailwind arbitrary values syntax? https://play.tailwindcss.com/fZw2FuH4Vo?file=config

**Comment by waldemarennsaed** [comment]
> Would this work? Using the tailwind arbitrary values syntax? https://play.tailwindcss.com/fZw2FuH4Vo?file=config

Yes, thats _exactly_ what I need. As long as I can define a single component by jsut swapping out the input (using string-literals like `[backgroundColor: ${WHITELABEL_THEME.color}] bg-dark`etc., I am totally fine with it. Thanks!

**Comment by nanorepublica** [comment]
Yep that should work. be sure that there isn't any whitespace though otherwise tailwind picks it up as separate classes. 

One other Tailwind feature you might benefit from in terms of whitelabeling is the presets functionality? https://tailwindcss.com/docs/presets. I would probably be using that if I had whitelabelling to do. But that of course entire depends on your solution which I have zero context for.

**Comment by waldemarennsaed** [comment]
> One other Tailwind feature you might benefit from in terms of whitelabeling is the presets functionality? https://tailwindcss.com/docs/presets. I would probably be using that if I had whitelabelling to do. But that of course entire depends on your solution which I have zero context for.

Already using it but I really appreciate your suggestions. In my case, we just have two custom classes (placed within the `components` layer of tailwindcss) that allow whitelabeling. The issue is, that for some whitelabels, we can just reference to our customized tailwind `bg-{color}` classes and for some whitelabels we must set _new_ colors via their value, e.g. `#123abc`.

My next issue would be to figure out a solution that allows me to just pass either a value or a tw-class without having to provide different structures that I then have to use to determine whether to use the arbitary-value syntax or just passing the class, but that's a different problem.
